import React, {FC} from 'react'
import Image from 'next/image'
import styles from '../../styles/Kwikeditor.module.css'
import Topbar from '../Topbar'
import Sidebar from '../Sidebar'
import Head from 'next/head'

interface Props {
    children: React.ReactChild[]
}

const CreatorLayout:FC<Props> = ({children}) => {
  return (
    <div>
      <Head>
        <title>Kwik Creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kwikifavicon.ico" />
      </Head>
      <Topbar/>
      <div className={styles['pContainer']}>
          {children}
      </div>
    </div>
  )
}

export default CreatorLayout