import React, { ReactNode, useEffect, useRef, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Topbar from './Topbar'
import Sidebar from './Sidebar'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/router'

interface Props {
    children: ReactNode,
}

export default function Layout({children}: Props) {
  
  const { data: session, status } = useSession()

  const router = useRouter()

  return ( 
    <div>
        <Head>
        <title>Kwik.com | Invoice Creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kwikifavicon.ico" />
      </Head>
      <div className={styles['parentContainer']}>
      <Topbar userEmail={status === "authenticated" ? session?.user?.email! : ""}/>
      <Sidebar/>
          {children}
      </div>
    </div>
  )
}


  /**const [bg, setBg] = useState<string>("")
  useEffect(() => {
    const handleScroll = (event: Event) => {
      setBg('#fff')
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []); */