import React, { ReactNode, useEffect, useRef, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Topbar from './Topbar'
import Sidebar from './Sidebar'
import { ClientContextProvider } from '../helper/context/clientContext/ClientContextprovider'

interface Props {
    children: ReactNode,
}

export default function Layout({children}: Props) {
  
  /**const [bg, setBg] = useState<string>("")
  useEffect(() => {
    const handleScroll = (event: Event) => {
      setBg('#fff')
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []); */

  return ( 
    <div>
        <Head>
        <title>Kwik.com | Invoices, Quotations and more...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kwikifavicon.ico" />
      </Head>
      <div className={styles['parentContainer']}>
      <Topbar/>
      <Sidebar/>
          {children}
      </div>
    </div>
  )
}