import React, { useRef, useEffect } from "react";
import styles from "../../styles/LandingPage.module.css";
import { motion } from "framer-motion";
import ButtonComponent from "../../components/Button";
import {
  AddBox,
  Email,
  EmailOutlined,
  Face,
  Facebook,
  FormatQuote,
  GiteSharp,
  GitHub,
  Instagram,
  Person,
  Twitter,
} from "@mui/icons-material";
import { useRouter } from "next/router";
import Head from "next/head";

//mini icon component

interface Props {
  icon: JSX.Element;
  className: string;
}

const MuiIcons = ({ icon, className }: Props) => {
  return <span className={className}>{icon}</span>;
};

//<img src="/kwik_logo.png" alt="" />
const landingpage = () => {
  const router = useRouter();
  const mainref = useRef<HTMLDivElement | null>(null);
  const header = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const mainbody = mainref.current! as HTMLDivElement
    mainbody.addEventListener("scroll", function(){
      console.log(scrollX, scrollY)
    })
  }, []);

  /**let maindiv = header.current as HTMLDivElement;
      scrollY > 0
        ? (maindiv.style.position = "fixed")
        : (maindiv.style.position = "relative"); */

  return (
    <div className={styles.main} ref={mainref}>
      <Head>
        <title>Kwik.com | Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kwikifavicon.ico" />
      </Head>

      <header className={styles.header} ref={header}>
        <div className={styles.logo}>
          <h2 className={styles["h2"]}>
            <span className={styles["text-color-primary-gradient"]}>
              KWIK.COM
            </span>
          </h2>
        </div>

        <div className={styles["nav-menu-wrapper"]}>
          <p className={styles["nav-link"]}>Features</p>
          <p className={styles["nav-link"]}>Customers</p>
          <p className={styles["nav-link"]}>Blog</p>
          <p className={styles["nav-link"]}>About</p>

          <div className={styles["nav-menu-cta"]}>
            <ButtonComponent
              className={styles["lpbtn"]}
              innerText="Login"
              onClick={() => router.push("/auth/login")}
            />
            <ButtonComponent
              className={styles["lpbtn"]}
              innerText="Sign up"
              onClick={() => router.push("/auth/register")}
            />
          </div>
        </div>
      </header>

      <section className={styles["hero-header"]}>
        <div className={styles["container"]}>
          <div className={styles["grid"]}>
            <motion.div
              id={styles["left"]}
              animate={{ x: 1 }}
              transition={{ type: "keyframes", ease: "circInOut" }}
            >
              <div className={styles["subtitle"]}>Welcome to Kwik.com</div>
              <h1 className={styles["display-heading-1"]}>
                General Purpose
                <span className={styles["text-color-primary-gradient"]}>
                  <br />
                  Invoice and Receipt Generator
                </span>
              </h1>
              <p className={styles["fulltext"]}>
                Kwik at this point is a small portfolio project, but don't let
                that fool you, kwik is ready to rumble in its' own domain. You
                can generate PDF and printable documents, designed to suite
                industry standards and easily customizable.
              </p>
              <div style={{ display: "flex", gap: "1rem" }}>
                <ButtonComponent
                  className={styles["lpbtn"]}
                  innerText="Get Started"
                />
                <ButtonComponent
                  className={styles["lpbtn"]}
                  innerText="Generate Invoice"
                />
              </div>

              <p className={styles["small-paragraph"]}>
                No credit card needed. Cancel anytime.
              </p>
            </motion.div>
            <img src="/leftsvg.png" width={650} />
          </div>
        </div>
      </section>

      <div className={styles["how-it-works-section"]}>
        <div className={styles["container"]}>
          <div className={styles["how-it-works-container"]}>
            <div id={styles["left"]} className={styles["how-it-works-left"]}>
              <div className={styles["subtitle"]}>Feature</div>
              <h2 className={styles["h2"]}>
                Kwik has a lot of features,{" "}
                <span className={styles["text-color-primary-gradient"]}>
                  cool features
                </span>
                .
              </h2>
              <p className={styles["p"]}>
                On the right is a list of the small amount of features that kwik
                curently-not limited to-has.
              </p>
              <ButtonComponent
                className={styles["lpbtn"]}
                innerText="Get Started"
              />
            </div>
            <div id={styles["left"]} className="how-it-works-right">
              <div id="left" className={styles["feature-item-box"]}>
                <MuiIcons icon={<Email />} className="feature-item-icon" />
                <h4 className={styles["h4"]}>Invoice Redistribution</h4>
                <p className={styles["p"]}>
                  Kwik Invoices are saved to the cloud, hence they are always
                  ready for resends in any format or styling that you choose.
                </p>
              </div>
              <div id={styles["left"]} className={styles["feature-item-box"]}>
                <MuiIcons icon={<Person />} className="feature-item-icon" />
                <h4 className={styles["h4"]}>Client Management</h4>
                <p className={styles["p"]}>
                  As a minimal addition to just creating and storing invoices.
                  Reoccuring client informations can be saved and referenced,
                  for new invoices.
                </p>
              </div>
              <div
                id={
                  styles[
                    "w-node-_61cf71b8-e0d5-34a3-4c17-9ecad9f647a5-9a7fc9e8"
                  ]
                }
                className={styles["feature-item-box"]}
              >
                <MuiIcons icon={<AddBox />} className="feature-item-icon" />
                <h4 className={styles["h4"]}>Product Mangament</h4>
                <p className={styles["p"]}>
                  Products can aslo be saved and targeted for new invoice
                  generation. You can select more than one products and generate
                  an invoice or invoices.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className={styles["_2-testimonials-section"]}>
        <div className={styles["container"]}>
          <div className={styles["_2-testimonials-container"]}>
            <h2 className={styles["h2"]}>
              Our customers love{" "}
              <span className={styles["text-color-primary-gradient"]}>
                Kwik.Com
              </span>
            </h2>
            <div className={styles["_2-testimonials-grid"]}>
              <div
                id={
                  styles[
                    "w-node-_6f1656bb-aceb-390a-ac27-0acfcfeb62d5-9a7fc9e8"
                  ]
                }
                className={styles["_2-testimonials-item"]}
              >
                <MuiIcons
                  className={styles["feature-item-icon"]}
                  icon={<FormatQuote />}
                />
                <div className={styles["_2-testimonials-quote"]}>
                  "Lorem ipsum dolor sit amet, consecur adipiscing elit ut
                  aliquam, purus sit amet luctus venenatis, lectus magna
                  fringilla urna, porttitor rhoncus dolor purus non enim
                  praesent elentum facilisis leo, vel fringilla."
                </div>
                <div className={styles["_2-testimonials-person"]}>
                  <MuiIcons
                    className={styles["feature-item-icon"]}
                    icon={<FormatQuote />}
                  />
                  <div
                    id="w-node-bb8ee3cd-98a1-6845-1f3c-a6717bf8a249-9a7fc9e8"
                    className={styles["_2-testimonials-person-details"]}
                  >
                    <div className={styles["_2-testimonials-person-name"]}>
                      Jessica Lee
                    </div>
                    <div className={styles["_2-testimonials-person-company"]}>
                      Job title at Company
                    </div>
                  </div>
                </div>
              </div>
              <div
                id={
                  styles[
                    "w-node-_6f1656bb-aceb-390a-ac27-0acfcfeb62d5-9a7fc9e8"
                  ]
                }
                className={styles["_2-testimonials-item"]}
              >
                <MuiIcons
                  className={styles["feature-item-icon"]}
                  icon={<FormatQuote />}
                />
                <div className={styles["_2-testimonials-quote"]}>
                  "Lorem ipsum dolor sit amet, consecur adipiscing elit ut
                  aliquam, purus sit amet luctus venenatis, lectus magna
                  fringilla urna, porttitor rhoncus dolor purus non enim
                  praesent elentum facilisis leo, vel fringilla."
                </div>
                <div className={styles["_2-testimonials-person"]}>
                  <MuiIcons
                    className={styles["feature-item-icon"]}
                    icon={<FormatQuote />}
                  />
                  <div
                    id={
                      styles[
                        "w-node-_6f1656bb-aceb-390a-ac27-0acfcfeb62d5-9a7fc9e8"
                      ]
                    }
                    className={styles["_2-testimonials-person-details"]}
                  >
                    <div className={styles["_2-testimonials-person-name"]}>
                      Jessica Lee
                    </div>
                    <div className={styles["_2-testimonials-person-company"]}>
                      Job title at Company
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <section className={styles["_3-grid-feature-section"]}>
        <div className={styles["container"]}>
          <div className={styles["_3-grid-feature-container"]}>
            <h2 className={styles["h2"]}>
              Why do customers use{" "}
              <span className={styles["text-color-primary-gradient"]}>
                Kwik.Com?
              </span>
            </h2>
          </div>
          <div className={styles["_3-grid-feature-grid"]}>
            <div
              id={
                styles["w-node-_61cf71b8-e0d5-34a3-4c17-9ecad9f647a5-9a7fc9e8"]
              }
              className={styles["feature-item-box"]}
            >
              <img src="" loading="lazy" alt="" className="feature-item-icon" />
              <h4 className={styles["h4"]}>Effieciency</h4>
              <p className={styles["p"]}>
                Kwik has been optimized to be fast in delivery due to its'
                defined data model.
              </p>
            </div>
            <div
              id={
                styles["w-node-_61cf71b8-e0d5-34a3-4c17-9ecad9f647a5-9a7fc9e8"]
              }
              className={styles["feature-item-box"]}
            >
              <img src="" loading="lazy" alt="" className="feature-item-icon" />
              <h4 className={styles["h4"]}>User Friendly</h4>
              <p className={styles["p"]}>
                Kwik has a very intuitive and user friendly interface, which
                means less resource spent learning. Simply start using.
              </p>
            </div>
            <div
              id={
                styles["w-node-_61cf71b8-e0d5-34a3-4c17-9ecad9f647a5-9a7fc9e8"]
              }
              className={styles["feature-item-box"]}
            >
              <img src="" loading="lazy" alt="" className="feature-item-icon" />
              <h4 className={styles["h4"]}>Minimal</h4>
              <p className={styles["p"]}>
                If you are looking for a compact invoice generator, Kwik is the
                right choice for you and your buisness.
              </p>
            </div>
          </div>
        </div>
      </section>

      <div className={styles["big-ui-feature-section"]}>
        <div className={styles["container"]}>
          <div className={styles["big-ui-feature-container"]}>
            <div className={styles["title-section"]}>
              <div className={styles["subtitle"]}>Implemetation</div>
              <h2 className={styles["h2"]}>
                Kwik is a React Nextjs and{" "}
                <span className={styles["text-color-primary-gradient"]}>
                  Typescript web Implementation
                </span>
                .
              </h2>
            </div>
            <div className={styles["big-ui-feature-main"]}>
              <img src="/hss.png" width={750} />
              <div
                id={
                  styles[
                    "w-node-_61cf71b8-e0d5-34a3-4c17-9ecad9f647a5-9a7fc9e8"
                  ]
                }
                className={styles["big-ui-feature-side"]}
              >
                <div
                  id={
                    styles[
                      "w-node-_61cf71b8-e0d5-34a3-4c17-9ecad9f647a5-9a7fc9e8"
                    ]
                  }
                  className={styles["big-feature-side-item"]}
                >
                  <img
                    src=""
                    loading="lazy"
                    alt=""
                    className={styles["big-feature-side-item-icon"]}
                  />
                  <h4 className={styles["h4"]}>Frontend</h4>
                  <p className={styles["p"]}>
                    Kwik uses the MERN frontend stack
                  </p>
                </div>
                <div
                  id={
                    styles[
                      "w-node-_61cf71b8-e0d5-34a3-4c17-9ecad9f647a5-9a7fc9e8"
                    ]
                  }
                  className={styles["big-feature-side-item"]}
                >
                  <img
                    src="https://assets.website-files.com/62c067dd72561e44087fc9ea/62c4c82e0cfd8db3cd599f25_big-feature-icon.svg"
                    loading="lazy"
                    alt=""
                    className={styles["big-feature-side-item-icon"]}
                  />
                  <h4 className={styles["h4"]}>Backend</h4>
                  <p className={styles["p"]}>
                    Kwik uses MongoDB NoSQL database to house its' data.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className={styles["footer-top"]}>
        <div className={styles["container"]}>
          <div className={styles["footer-top-wrapper"]}>
            <div className={styles["footer-top-left"]}>
              <div className={styles["footer-logo"]}>
                <h2 className={styles["h2"]}>
                  <span className={styles["text-color-primary-gradient"]}>
                    KWIK.COM
                  </span>
                </h2>
              </div>
              <p>Efficiency and simplicity at its' finest.</p>
              <div className={styles["footer-social-links"]}>
                <a
                  href="#"
                  className={styles["footer-social-link-button w-inline-block"]}
                >
                  <Facebook />
                </a>
                <a
                  href="#"
                  className={styles["footer-social-link-button w-inline-block"]}
                >
                  <Instagram />
                </a>
                <a
                  href="#"
                  className={styles["footer-social-link-button w-inline-block"]}
                >
                  <EmailOutlined />
                </a>
                <a
                  href="#"
                  className={styles["footer-social-link-button w-inline-block"]}
                >
                  <GiteSharp />
                </a>
              </div>
            </div>
            <div className={styles["footer-top-links"]}>
              <div
                id={
                  styles[
                    "w-node-_61cf71b8-e0d5-34a3-4c17-9ecad9f647a5-9a7fc9e8"
                  ]
                }
                className={styles["footer-top-links-column"]}
              >
                <div className={styles["footer-top-links-title"]}>Hilights</div>
                <a
                  id={
                    styles[
                      "w-node-_61cf71b8-e0d5-34a3-4c17-9ecad9f647a5-9a7fc9e8"
                    ]
                  }
                  href="/"
                  aria-current="page"
                  className={styles["footer-top-link w--current"]}
                >
                  Home
                </a>
                <a href="/features" className={styles["footer-top-link"]}>
                  Features
                </a>
                <a href="/pricing" className={styles["footer-top-link"]}>
                  Comments
                </a>
                <a href="/about" className={styles["footer-top-link"]}>
                  Customer Satisafction
                </a>
                <a href="/blog" className={styles["footer-top-link"]}>
                  Blog
                </a>
              </div>

              <div
                id="w-node-e7ba1ad8-82c9-04e4-ca70-e1670d3cc182-19f04aa8"
                className={styles["footer-top-links-column"]}
              >
                <div className={styles["footer-top-links-title"]}>Extra</div>
                <a href="/styleguide" className={styles["footer-top-link"]}>
                  Style Guide
                </a>
                <a href="/licenses" className={styles["footer-top-link"]}>
                  Licenses
                </a>
                <a href="/changelog" className={styles["footer-top-link"]}>
                  Changelog
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className={styles["footer-bottom"]}>
        <div className={styles["container"]}>
          <div className={styles["footer-bottom-container"]}>
            <div>
              © Designed by{" "}
              <a
                href="https://webflow.com/templates/designers/wan-studio"
                target="_blank"
                className="text-link"
              >
                Ezene Frank
              </a>
            </div>
            <div>
              Powered by{" "}
              <a
                href="http://webflow.com"
                target="_blank"
                className="text-link"
              >
                Protek
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default landingpage;

/****
 import React from 'react'
import renderer from 'react-test-renderer'
import { Provider } from 'react-redux'

import store from '~/store'
import {  } from '../'

describe('< />', () => {
  const defaultProps = {}
  const wrapper = renderer.create(
    <Provider store={store}>
     < {...defaultProps} />
    </Provider>,
  )

  test('render', () => {
    expect(wrapper).toMatchSnapshot()
  })
})
 */
